// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateAccount legt das Konto in der DB an (nur Verbindungsdaten, kein
 * Passwort) und speichert die Passwörter getrennt im OS-Schlüsselbund.
 */
export function CreateAccount($in: $models.AccountInput): $CancellablePromise<$models.AccountView> {
    return $Call.ByID(3979687645, $in);
}

/**
 * DeleteAccount entfernt ein Konto samt aller lokal gespeicherten Mails
 * (kaskadiert in der DB) und den zugehörigen Passwörtern im Schlüsselbund.
 */
export function DeleteAccount(id: number): $CancellablePromise<void> {
    return $Call.ByID(146619280, id);
}

/**
 * GetAccountDetails liefert die Verbindungsdaten eines Kontos für das
 * Bearbeiten-Formular — ohne Passwörter, siehe AccountEditView.
 */
export function GetAccountDetails(id: number): $CancellablePromise<$models.AccountEditView> {
    return $Call.ByID(4029160813, id);
}

export function ListAccounts(): $CancellablePromise<$models.AccountView[] | null> {
    return $Call.ByID(2760578426);
}

/**
 * SyncAll synchronisiert alle Konten nacheinander (Post/Ablage/Pförtner
 * sind ein gemeinsames Postfach über alle Konten hinweg). Ein
 * fehlschlagendes Konto (z. B. falsches Passwort) bricht die anderen
 * nicht ab — Fehler werden gesammelt und am Ende gemeinsam gemeldet.
 */
export function SyncAll(): $CancellablePromise<number> {
    return $Call.ByID(695899764);
}

/**
 * SyncNow ruft neue Mails ab und sortiert sie in Post/Ablage/Pförtner ein.
 */
export function SyncNow(accountID: number): $CancellablePromise<number> {
    return $Call.ByID(510190215, accountID);
}

/**
 * TestIMAP prüft Host/Port/Zugangsdaten, ohne etwas zu speichern —
 * für den "Verbindung testen"-Button im Formular.
 */
export function TestIMAP($in: $models.AccountInput): $CancellablePromise<void> {
    return $Call.ByID(3348406113, $in);
}

export function TestSMTP($in: $models.AccountInput): $CancellablePromise<void> {
    return $Call.ByID(3546190138, $in);
}

/**
 * UpdateAccount ändert Label, Anzeigename und Verbindungsdaten eines
 * bestehenden Kontos. Die Passwortfelder in AccountInput sind hier
 * optional — leer gelassen, bleibt das im Schlüsselbund gespeicherte
 * Passwort unangetastet, statt es zu löschen oder mit "" zu überschreiben.
 */
export function UpdateAccount(id: number, $in: $models.AccountInput): $CancellablePromise<$models.AccountView> {
    return $Call.ByID(592440522, id, $in);
}
