// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteMail verschiebt eine IMAP-Mail zuerst serverseitig in den
 * Papierkorb und entfernt erst danach die lokale Kopie. Rein lokale
 * Gesendet-Kopien (ohne Server-UID) können direkt entfernt werden.
 */
export function DeleteMail(mailID: number): $CancellablePromise<void> {
    return $Call.ByID(1737605678, mailID);
}

/**
 * Entscheiden setzt Freigabe ("post") oder Sperrung. Gesperrte Absender
 * erreichen ab dem nächsten Sync weder Post noch den Pförtner — siehe
 * internal/mail/sync.go.
 */
export function Entscheiden(accountID: number, email: string, freigeben: boolean): $CancellablePromise<void> {
    return $Call.ByID(1756102612, accountID, email, freigeben);
}

export function GetAblage(): $CancellablePromise<$models.MailView[] | null> {
    return $Call.ByID(903512330);
}

/**
 * GetGesendet liefert lokal versendete Mails — anders als Post/Ablage kommt
 * dieser Ordner nie aus einem IMAP-Sync, sondern wird direkt beim
 * erfolgreichen SendMail befüllt (siehe dort). Sender/Initials/AvatarColor
 * beziehen sich hier bewusst auf den (ersten) Empfänger statt auf den
 * Absender — in der eigenen "Gesendet"-Ansicht ist ja immer man selbst der
 * Absender, interessant ist, an wen die Mail ging.
 */
export function GetGesendet(): $CancellablePromise<$models.MailView[] | null> {
    return $Call.ByID(1960745457);
}

/**
 * GetMail liefert den vollen Inhalt einer Mail und markiert sie als
 * gelesen — der Klartext (body_text) wird bereits beim Sync erzeugt,
 * siehe internal/mail/sanitize.go.
 */
export function GetMail(mailID: number): $CancellablePromise<$models.MailDetailView> {
    return $Call.ByID(1599863013, mailID);
}

export function GetPfoertner(): $CancellablePromise<$models.PendingView[] | null> {
    return $Call.ByID(1315158675);
}

export function GetPost(): $CancellablePromise<$models.MailView[] | null> {
    return $Call.ByID(2151850168);
}

/**
 * MoveToAblage verschiebt eine Mail von Post nach Ablage.
 */
export function MoveToAblage(mailID: number): $CancellablePromise<void> {
    return $Call.ByID(400685742, mailID);
}

/**
 * MoveToPost verschiebt eine Mail von Ablage zurück nach Post.
 */
export function MoveToPost(mailID: number): $CancellablePromise<void> {
    return $Call.ByID(16216580, mailID);
}

/**
 * OpenExternalLink öffnet einen Link aus einer Mail im Standardbrowser
 * des Systems, nie innerhalb von f:mail selbst — das HTML-Rendering läuft
 * in einem sandboxed iframe ohne Navigations-Erlaubnis (siehe
 * frontend/src/main.js), Klicks darin werden hierher umgeleitet. Nur
 * http/https/mailto zugelassen, alles andere (z. B. file:) wird abgelehnt.
 */
export function OpenExternalLink(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(823508413, rawURL);
}

/**
 * SaveAttachment öffnet einen nativen "Speichern unter"-Dialog und
 * schreibt den Anhang an die gewählte Stelle. Bewusst kein automatisches
 * Öffnen der Datei — der Nutzer entscheidet aktiv, wo sie landet, statt
 * dass f:mail sie irgendwo (z. B. temp) ablegt und einen Öffnen-Handler
 * dafür aufruft. Ein leerer Rückgabewert bedeutet "abgebrochen", kein Fehler.
 */
export function SaveAttachment(attachmentID: number): $CancellablePromise<string> {
    return $Call.ByID(1079976658, attachmentID);
}

/**
 * SendMail verschickt eine Mail über das SMTP-Konto, optional als HTML
 * (bodyHTML != "", body dient dann als Klartext-Fallback für
 * multipart/alternative) und/oder mit Anhängen.
 */
export function SendMail(accountID: number, to: string[] | null, subject: string, body: string, bodyHTML: string, attachments: $models.AttachmentInput[] | null): $CancellablePromise<void> {
    return $Call.ByID(3803564399, accountID, to, subject, body, bodyHTML, attachments);
}
