// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountEditView liefert die Verbindungsdaten eines Kontos zurück, um
 * das Bearbeiten-Formular vorzubefüllen — bewusst ohne Passwörter, die
 * bleiben ausschließlich im Schlüsselbund.
 */
export interface AccountEditView {
    "id": number;
    "label": string;
    "email": string;
    "displayName": string;
    "imapHost": string;
    "imapPort": number;
    "imapSecurity": string;
    "imapUsername": string;
    "smtpHost": string;
    "smtpPort": number;
    "smtpSecurity": string;
    "smtpUsername": string;
    "syncIntervalMinutes": number;
}

/**
 * AccountInput kommt 1:1 aus dem Kontoformular im Frontend.
 */
export interface AccountInput {
    "label": string;
    "email": string;

    /**
     * Absendername ("Von"), z. B. "Frank Lewandowski"
     */
    "displayName": string;
    "imapHost": string;
    "imapPort": number;

    /**
     * "tls" | "starttls"
     */
    "imapSecurity": string;
    "imapUsername": string;
    "imapPassword": string;
    "smtpHost": string;
    "smtpPort": number;
    "smtpSecurity": string;
    "smtpUsername": string;
    "smtpPassword": string;

    /**
     * 0 = nur manueller Sync
     */
    "syncIntervalMinutes": number;
}

export interface AccountView {
    "id": number;
    "label": string;
    "email": string;
    "displayName": string;
    "syncIntervalMinutes": number;
}

/**
 * AttachmentInput kommt aus dem Compose-Formular im Frontend — Data ist
 * Base64-kodiert, weil FileReader im Browser Dateien so über die
 * Wails-Bindings-Grenze (JSON) an Go übergibt.
 */
export interface AttachmentInput {
    "filename": string;
    "contentType": string;
    "data": string;
}

/**
 * AttachmentView beschreibt einen Anhang ohne seinen Inhalt (siehe
 * store.ListAttachments) — der Inhalt wird erst beim tatsächlichen
 * Speichern geladen, siehe SaveAttachment.
 */
export interface AttachmentView {
    "id": number;
    "filename": string;
    "contentType": string;
    "size": number;
}

export interface MailDetailView {
    "id": number;
    "accountId": number;
    "accountLabel": string;
    "sender": string;
    "senderEmail": string;
    "initials": string;
    "avatarColor": string;
    "brandIcon": string;
    "subject": string;
    "body": string;

    /**
     * leer, wenn die Mail keine HTML-Variante hatte -> Frontend zeigt dann Body als Klartext
     */
    "bodyHtml": string;
    "date": string;
    "hasAttachment": boolean;
    "folder": string;

    /**
     * nur bei Folder "gesendet" befüllt
     */
    "recipients": string[] | null;
    "attachments": AttachmentView[] | null;
}

export interface MailView {
    "id": number;
    "accountId": number;
    "accountLabel": string;

    /**
     * bei Folder "gesendet": die Empfänger (kommagetrennt), nicht der Absender — siehe GetGesendet
     */
    "sender": string;
    "initials": string;
    "avatarColor": string;

    /**
     * z. B. "github" — leer, wenn Absender-Domain nicht erkannt
     */
    "brandIcon": string;
    "subject": string;
    "preview": string;
    "date": string;
    "unread": boolean;
    "hasAttachment": boolean;
}

export interface PendingView {
    /**
     * "<accountId>:<E-Mail>" — eindeutig über alle Konten, dient als Frontend-Schlüssel
     */
    "id": string;
    "accountId": number;
    "accountLabel": string;
    "name": string;
    "email": string;
    "initials": string;
    "avatarColor": string;
    "brandIcon": string;
    "subject": string;
    "preview": string;
}
